### PR TITLE
Various improvements for readpe

### PR DESCRIPTION
**Pull request by pali**
* Add new machines types
* Add image characteristic IMAGE_FILE_16BIT_MACHINE
* Add missing image dll characteristics
* Add missing subsystems
* Recognize all known section characteristics
* Add support for parsing loader flags
* Validate size of PE optional header
* Add support for parsing long section names
* Add support for parsing PE object files
* Add support for parsing PE ROM files
* Add machine type for old Alpha
* Add IMAGE_FILE_MACHINE_OMNI
* Add support for parsing Win32VersionValue
* Update information about IMAGE_FILE_BYTES_REVERSED
* Remove NE signature check
* Show PE signature if present in readpe output

### CODE REVIEW

**Comment by pali** [comment]
@GoGoOtaku if you need some help or some explanation of something there, just ask me.

**Comment by GoGoOtaku** [comment]
First of all: Thank you very much for this.

My biggest issue is that I know very little about PE ROMs and none of my test executables are ROMs.
That said I don't have any problems with the code per se. I have flagged up an if block and that's about it.

I didn't like `pe_dll_image_dllcharacteristic_name` as a function name.
I do understand tho that `IMAGE_DLLCHARACTERISTICS_X86_THUNK` and `IMAGE_DLLCHARACTERISTICS_APPCONTAINER`
cause this. Overall I think I just accept the weird name tho so that's fine.

And again thank you very much.

**Comment by pali** [comment]
> none of my test executables are ROMs

You can generate x86 PE ROM binary very easily by MSVC4 linker.
Use simple test.c file `int main() { return 0; }` and run `CL.EXE test.c /link /ROM /ENTRY:main`

Other machine types can be generated by flags:
* PowerPC little-endian: `LINK.EXE /MACHINE:powerpc /ROM`
* PowerPC big-endian: `LINK.EXE /MACHINE:MPPC /ROM`
* Alpha 32-bit: `LINK.EXE /MACHINE:ALPHA /ROM`
* MIPS: `LINK.EXE /MACHINE:MIPSR10 /ROM`

But you need either compiler for those machine types or you can use a trick that MSVC linker can take also binary resource file and generate from it PE executable. Flags like `/ENTRY:0` or `/FORCE` can be useful for playing with it.

> I didn't like `pe_dll_image_dllcharacteristic_name` as a function name.

Feel free to invent other / better name and rename the function.

**Comment by GoGoOtaku** [comment]
> Feel free to invent other / better name and rename the function.
It's ok

This is merged now

**Comment by GoGoOtaku** [comment]
I merged manually due to some conflicts and github doesn't like this

**Pull request closed without merging**
